# Generated by Django 4.0 on 2021-12-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд>',
                'verbose_name_plural': 'Бренды',
                'db_table': 'brand',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.brand', verbose_name='Бренд'),
        ),
    ]
